// SPDX-License-Identifier: GPL-3.0-only

use super::model::{SlashCommandDescriptor, SlashCommandPermission, SlashCommandSurface};

pub(super) const SLASH_COMMAND_REGISTRY_SCHEMA: &str = "ikaros-workbench-commands-v1";
pub(super) const SLASH_COMMAND_REGISTRY_VERSION: u32 = 3;
pub(super) const SLASH_COMMAND_REGISTRY_SOURCE: &str = "builtin";

const READ: &[SlashCommandPermission] = &[SlashCommandPermission::Read];
const SESSION_CONTROL: &[SlashCommandPermission] = &[SlashCommandPermission::SessionControl];
const AGENT_CONTROL: &[SlashCommandPermission] = &[SlashCommandPermission::AgentControl];
const PROVIDER_READ: &[SlashCommandPermission] = &[
    SlashCommandPermission::Provider,
    SlashCommandPermission::Network,
];
const MCP: &[SlashCommandPermission] = &[
    SlashCommandPermission::Read,
    SlashCommandPermission::Network,
    SlashCommandPermission::Approval,
];
const CONFIG_WRITE: &[SlashCommandPermission] = &[SlashCommandPermission::Config];
const APPROVAL: &[SlashCommandPermission] = &[SlashCommandPermission::Approval];
const WORKSPACE_READ: &[SlashCommandPermission] = &[SlashCommandPermission::Read];
const CODING_WRITE: &[SlashCommandPermission] = &[
    SlashCommandPermission::Coding,
    SlashCommandPermission::WorkspaceWrite,
    SlashCommandPermission::Shell,
];
const CODING_READ: &[SlashCommandPermission] =
    &[SlashCommandPermission::Read, SlashCommandPermission::Coding];
const WORKBENCH_ONLY: &[SlashCommandSurface] = &[SlashCommandSurface::Workbench];
const WORKBENCH_GATEWAY: &[SlashCommandSurface] =
    &[SlashCommandSurface::Workbench, SlashCommandSurface::Gateway];
const WORKBENCH_GATEWAY_ACP: &[SlashCommandSurface] = &[
    SlashCommandSurface::Workbench,
    SlashCommandSurface::Gateway,
    SlashCommandSurface::Acp,
];

const SLASH_COMMANDS: &[SlashCommandDescriptor] = &[
    SlashCommandDescriptor {
        name: "/help",
        usage: "/help",
        summary: "show workbench commands",
        tags: &["commands", "help"],
        permissions: READ,
        surfaces: WORKBENCH_GATEWAY_ACP,
    },
    SlashCommandDescriptor {
        name: "/commands",
        usage: "/commands [query] [--json|--markdown|--palette]",
        summary: "search slash command registry and export machine-readable metadata or command-palette groups",
        tags: &[
            "commands", "search", "fuzzy", "registry", "metadata", "palette",
        ],
        permissions: READ,
        surfaces: WORKBENCH_GATEWAY_ACP,
    },
    SlashCommandDescriptor {
        name: "/queue",
        usage: "/queue [message|run|drain|continue|clear|remove N|retry ID|requeue ID]",
        summary: "inspect, run, enqueue, remove, clear, or requeue pending work",
        tags: &["input", "pending", "queue", "resume"],
        permissions: SESSION_CONTROL,
        surfaces: WORKBENCH_GATEWAY,
    },
    SlashCommandDescriptor {
        name: "/attach",
        usage: "/attach image <url-or-path> [--detail low|high|auto] | <audio|file> <url-or-path> | list | remove <index> | clear",
        summary: "queue multimodal content blocks for the next chat turn",
        tags: &[
            "input",
            "attachment",
            "image",
            "detail",
            "audio",
            "file",
            "multimodal",
        ],
        permissions: SESSION_CONTROL,
        surfaces: WORKBENCH_ONLY,
    },
    SlashCommandDescriptor {
        name: "/agents",
        usage: "/agents",
        summary: "list configured agent profiles and instances",
        tags: &["agent", "profile", "instance"],
        permissions: READ,
        surfaces: WORKBENCH_GATEWAY_ACP,
    },
    SlashCommandDescriptor {
        name: "/agent",
        usage: "/agent <profile-or-instance>",
        summary: "switch active agent profile or instance",
        tags: &["agent", "profile", "instance"],
        permissions: AGENT_CONTROL,
        surfaces: WORKBENCH_ONLY,
    },
    SlashCommandDescriptor {
        name: "/status",
        usage: "/status",
        summary: "show unified workbench status",
        tags: &["session", "provider", "gateway", "approval"],
        permissions: READ,
        surfaces: WORKBENCH_GATEWAY_ACP,
    },
    SlashCommandDescriptor {
        name: "/budget",
        usage: "/budget [show|set <tokens>|disable]",
        summary: "inspect or update model.default.daily_token_budget",
        tags: &["model", "budget", "config", "tokens"],
        permissions: CONFIG_WRITE,
        surfaces: WORKBENCH_ONLY,
    },
    SlashCommandDescriptor {
        name: "/screen",
        usage: "/screen [--focus status|timeline|main|side] [--scroll N] [--select N] [--select-title title] [--select-kind kind] [--select-action command] [--palette [query]|--palette-query query|--close-palette] [--down|--up|--page-down|--page-up|--top] [--fullscreen|--inline] [--raw|--rich] [approve-selected|deny-selected|cancel-selected|clear-selected|open-selected|confirm-selected]",
        summary: "refresh a navigable terminal workbench screen and open or act on the selected cell",
        tags: &[
            "terminal",
            "screen",
            "status",
            "timeline",
            "approval",
            "continuation",
            "queue",
            "open",
            "focus",
            "scroll",
            "select",
            "palette",
        ],
        permissions: READ,
        surfaces: WORKBENCH_ONLY,
    },
    SlashCommandDescriptor {
        name: "/history",
        usage: "/history [limit]",
        summary: "show persisted workbench input history",
        tags: &["terminal", "history", "readline"],
        permissions: READ,
        surfaces: WORKBENCH_ONLY,
    },
    SlashCommandDescriptor {
        name: "/sessions",
        usage: "/sessions",
        summary: "list recent chat sessions",
        tags: &["session", "history"],
        permissions: READ,
        surfaces: WORKBENCH_GATEWAY_ACP,
    },
    SlashCommandDescriptor {
        name: "/session",
        usage: "/session status|resume|history|timeline|export [path]",
        summary: "inspect current session state, history, timeline, or explicit resume/export actions",
        tags: &["session", "resume", "timeline", "export"],
        permissions: SESSION_CONTROL,
        surfaces: WORKBENCH_GATEWAY_ACP,
    },
    SlashCommandDescriptor {
        name: "/resume",
        usage: "/resume <session>",
        summary: "resume a session id",
        tags: &["session", "resume"],
        permissions: SESSION_CONTROL,
        surfaces: WORKBENCH_GATEWAY_ACP,
    },
    SlashCommandDescriptor {
        name: "/new",
        usage: "/new",
        summary: "alias for /clear",
        tags: &["session", "alias"],
        permissions: SESSION_CONTROL,
        surfaces: WORKBENCH_GATEWAY_ACP,
    },
    SlashCommandDescriptor {
        name: "/fork",
        usage: "/fork [summary]",
        summary: "branch the current session from its active leaf",
        tags: &["session", "branch", "tree"],
        permissions: SESSION_CONTROL,
        surfaces: WORKBENCH_GATEWAY_ACP,
    },
    SlashCommandDescriptor {
        name: "/timeline",
        usage: "/timeline [turn] [--page N] [--kind KIND] [--failed|--approval]",
        summary: "show recent session timeline cells, optionally filtered by event kind or replay point",
        tags: &[
            "session", "replay", "debug", "kind", "filter", "failed", "approval",
        ],
        permissions: READ,
        surfaces: WORKBENCH_GATEWAY_ACP,
    },
    SlashCommandDescriptor {
        name: "/replay",
        usage: "/replay [turn] [--page N] [--kind KIND] [--failed|--approval]",
        summary: "show a longer session replay view, optionally filtered by event kind or replay point",
        tags: &["session", "replay", "kind", "filter", "failed", "approval"],
        permissions: READ,
        surfaces: WORKBENCH_GATEWAY_ACP,
    },
    SlashCommandDescriptor {
        name: "/debug",
        usage: "/debug [turn|readiness|sandbox [--probe]|logs|insights|dump|state-db|continuations] [--page N] [--kind KIND] [--failed|--approval]",
        summary: "show session debug cells, readiness, sandbox, logs, insights, dump, state-db, or continuation diagnostics",
        tags: &[
            "session",
            "debug",
            "readiness",
            "sandbox",
            "probe",
            "logs",
            "insights",
            "dump",
            "state-db",
            "continuations",
            "kind",
            "filter",
            "failed",
            "approval",
        ],
        permissions: READ,
        surfaces: WORKBENCH_ONLY,
    },
    SlashCommandDescriptor {
        name: "/sandbox",
        usage: "/sandbox [--probe]",
        summary: "show sandbox, process, environment, and network execution diagnostics",
        tags: &[
            "sandbox",
            "execution",
            "network",
            "process",
            "debug",
            "probe",
        ],
        permissions: READ,
        surfaces: WORKBENCH_ONLY,
    },
    SlashCommandDescriptor {
        name: "/trace",
        usage: "/trace [turn] [--kind KIND] [--failed|--approval]",
        summary: "show sanitized session trace spans, optionally filtered by event kind or replay point",
        tags: &[
            "session", "debug", "trace", "replay", "kind", "filter", "failed", "approval",
        ],
        permissions: READ,
        surfaces: WORKBENCH_GATEWAY_ACP,
    },
    SlashCommandDescriptor {
        name: "/mentions",
        usage: "/mentions [query]",
        summary: "search file, folder, git, diff, and staged context mentions",
        tags: &["context", "file", "folder", "mention", "reference"],
        permissions: WORKSPACE_READ,
        surfaces: WORKBENCH_GATEWAY_ACP,
    },
    SlashCommandDescriptor {
        name: "/context",
        usage: "/context",
        summary: "inspect context budget and prompt assembly state",
        tags: &["context"],
        permissions: READ,
        surfaces: WORKBENCH_GATEWAY_ACP,
    },
    SlashCommandDescriptor {
        name: "/memory",
        usage: "/memory",
        summary: "inspect memory policy, projection, and working-memory state",
        tags: &["memory"],
        permissions: READ,
        surfaces: WORKBENCH_GATEWAY_ACP,
    },
    SlashCommandDescriptor {
        name: "/rag",
        usage: "/rag",
        summary: "show RAG settings",
        tags: &["rag", "context"],
        permissions: READ,
        surfaces: WORKBENCH_GATEWAY_ACP,
    },
    SlashCommandDescriptor {
        name: "/tools",
        usage: "/tools",
        summary: "show direct and deferred model toolsets",
        tags: &["tool", "toolset", "skill"],
        permissions: READ,
        surfaces: WORKBENCH_GATEWAY_ACP,
    },
    SlashCommandDescriptor {
        name: "/mcp",
        usage: "/mcp status|call-stdio <command> <tool>|call-http <url> <tool>",
        summary: "show configured MCP servers or call stdio/HTTP MCP tools through harness boundaries",
        tags: &["mcp", "tool", "server", "status", "plugin", "stdio", "http"],
        permissions: MCP,
        surfaces: WORKBENCH_GATEWAY_ACP,
    },
    SlashCommandDescriptor {
        name: "/api",
        usage: "/api status",
        summary: "show local OpenAI-compatible API routes and readiness",
        tags: &["api", "openai", "responses", "embedding", "status"],
        permissions: READ,
        surfaces: WORKBENCH_GATEWAY_ACP,
    },
    SlashCommandDescriptor {
        name: "/browser",
        usage: "/browser [launch [url] [--profile NAME]|supervisor-status [--profile NAME]|stop [--profile NAME]|status|list|new <url>|activate <target-id>|close <target-id>|navigate <target-id> <url>|snapshot <target-id>|click <target-id> <x> <y>|type <target-id> <text>|scroll <target-id> [x] [y]|screenshot <target-id>|cdp <target-id> <method> [params-json]] [--endpoint URL]",
        summary: "launch or control a local Chrome DevTools endpoint with an isolated profile",
        tags: &[
            "browser",
            "cdp",
            "network",
            "debug",
            "supervisor",
            "profile",
        ],
        permissions: MCP,
        surfaces: WORKBENCH_GATEWAY_ACP,
    },
    SlashCommandDescriptor {
        name: "/web",
        usage: "/web search <query> [--provider duckduckgo-html|brave|bing|serpapi|tavily] [--max-results N] | /web extract <url> [--max-bytes N] [--max-chars N]",
        summary: "run governed web search or single-page extraction from workbench",
        tags: &["web", "search", "extract", "network"],
        permissions: MCP,
        surfaces: WORKBENCH_GATEWAY_ACP,
    },
    SlashCommandDescriptor {
        name: "/vision",
        usage: "/vision describe <image-path|url|data-url> [--prompt TEXT] [--detail low|high|auto]",
        summary: "describe an image through the active multimodal model",
        tags: &["vision", "image", "multimodal", "model"],
        permissions: PROVIDER_READ,
        surfaces: WORKBENCH_GATEWAY_ACP,
    },
    SlashCommandDescriptor {
        name: "/image",
        usage: "/image generate <prompt> [--model MODEL] [--size 1024x1024] [--n N] [--response-format url|b64_json] [--output-dir PATH]",
        summary: "generate images through the active OpenAI-compatible provider endpoint",
        tags: &["image", "generation", "multimodal", "model"],
        permissions: PROVIDER_READ,
        surfaces: WORKBENCH_GATEWAY_ACP,
    },
    SlashCommandDescriptor {
        name: "/model",
        usage: "/model",
        summary: "inspect active model descriptor",
        tags: &["provider", "model"],
        permissions: READ,
        surfaces: WORKBENCH_GATEWAY_ACP,
    },
    SlashCommandDescriptor {
        name: "/provider",
        usage: "/provider [inspect|health [--live]|matrix [--live] [--json]|profiles|debug]",
        summary: "inspect provider metadata, health, matrix, or debug JSON",
        tags: &["provider", "model", "health", "matrix", "json", "debug"],
        permissions: PROVIDER_READ,
        surfaces: WORKBENCH_GATEWAY_ACP,
    },
    SlashCommandDescriptor {
        name: "/gateway",
        usage: "/gateway [status|daemon status|daemon start|daemon stop|daemon restart|adapter list|adapter enqueue|adapter render-delivery]",
        summary: "show local gateway status, control the message daemon, or inspect platform adapters",
        tags: &["gateway", "ingress", "daemon", "adapter", "pairing"],
        permissions: READ,
        surfaces: WORKBENCH_GATEWAY_ACP,
    },
    SlashCommandDescriptor {
        name: "/tasks",
        usage: "/tasks",
        summary: "show scheduled task status",
        tags: &["schedule", "task"],
        permissions: READ,
        surfaces: WORKBENCH_GATEWAY_ACP,
    },
    SlashCommandDescriptor {
        name: "/approval",
        usage: "/approval [approve|deny <id>]",
        summary: "show or resolve pending approvals",
        tags: &["approval", "policy"],
        permissions: APPROVAL,
        surfaces: WORKBENCH_GATEWAY_ACP,
    },
    SlashCommandDescriptor {
        name: "/approvals",
        usage: "/approvals [approve|deny <id>]",
        summary: "alias for /approval",
        tags: &["approval", "policy", "alias"],
        permissions: APPROVAL,
        surfaces: WORKBENCH_GATEWAY_ACP,
    },
    SlashCommandDescriptor {
        name: "/cancel",
        usage: "/cancel [all|<continuation-id>]",
        summary: "cancel queued or running workbench continuations",
        tags: &["interrupt", "queue", "continuation", "cancel"],
        permissions: SESSION_CONTROL,
        surfaces: WORKBENCH_ONLY,
    },
    SlashCommandDescriptor {
        name: "/diff",
        usage: "/diff",
        summary: "show current git diff summary",
        tags: &["coding", "diff"],
        permissions: WORKSPACE_READ,
        surfaces: WORKBENCH_GATEWAY_ACP,
    },
    SlashCommandDescriptor {
        name: "/code",
        usage: "/code <plan|apply|test|review|rollback> ...",
        summary: "run coding workflow commands",
        tags: &["coding", "patch", "test", "review"],
        permissions: CODING_WRITE,
        surfaces: WORKBENCH_ONLY,
    },
    SlashCommandDescriptor {
        name: "/review",
        usage: "/review [--diff DIFF] [--test-analysis-json JSON]",
        summary: "alias for /code review",
        tags: &["coding", "review", "alias"],
        permissions: CODING_READ,
        surfaces: WORKBENCH_ONLY,
    },
    SlashCommandDescriptor {
        name: "/rollback",
        usage: "/rollback <session-id> --turn-id <turn-id>",
        summary: "alias for /code rollback",
        tags: &["coding", "rollback", "alias"],
        permissions: CODING_WRITE,
        surfaces: WORKBENCH_ONLY,
    },
    SlashCommandDescriptor {
        name: "/multi",
        usage: "/multi",
        summary: "enter multiline message mode",
        tags: &["input", "multiline"],
        permissions: READ,
        surfaces: WORKBENCH_ONLY,
    },
    SlashCommandDescriptor {
        name: "/clear",
        usage: "/clear",
        summary: "acknowledge a clear-screen request",
        tags: &["display"],
        permissions: READ,
        surfaces: WORKBENCH_ONLY,
    },
    SlashCommandDescriptor {
        name: "/quit",
        usage: "/quit",
        summary: "exit the workbench",
        tags: &["exit"],
        permissions: READ,
        surfaces: WORKBENCH_ONLY,
    },
    SlashCommandDescriptor {
        name: "/exit",
        usage: "/exit",
        summary: "alias for /quit",
        tags: &["exit", "alias"],
        permissions: READ,
        surfaces: WORKBENCH_ONLY,
    },
];

pub(super) fn slash_commands() -> &'static [SlashCommandDescriptor] {
    SLASH_COMMANDS
}
