// SPDX-License-Identifier: GPL-3.0-only

use super::types::{GatewayDrainContext, GatewayDrainReport};
use crate::{
    ChatRunOptions, TaskRunOptions, execute_task_text_with_options, run_chat_message,
    task_report_succeeded, task_report_summary,
};
use ikaros_core::{IkarosPaths, Result, redact_secrets};
use ikaros_gateway::{GatewayMessage, GatewayMessageKind, GatewayMessageStatus, LocalGatewayStore};
use ikaros_harness::TaskExecutionReport;
use ikaros_session::{AgentEventKind, AgentEventSource, SessionEntryKind};
use serde_json::json;
use std::path::Path;

use crate::session::{
    RuntimeSessionEntryInput, active_leaf_entry_id, append_runtime_session_entry,
    append_runtime_session_event, delivery_payload, gateway_message_kind, gateway_session_id,
    gateway_session_source, gateway_turn_id, runtime_session_target, upsert_runtime_session,
};

pub async fn drain_gateway_messages(
    messages: Vec<GatewayMessage>,
    store: &LocalGatewayStore,
    paths: &IkarosPaths,
    workspace: &Path,
    agent_override: Option<&str>,
) -> Result<Vec<GatewayDrainReport>> {
    let mut reports = Vec::new();
    for message in messages {
        reports
            .push(drain_gateway_message(message, store, paths, workspace, agent_override).await?);
    }
    Ok(reports)
}

pub async fn drain_gateway_message(
    message: GatewayMessage,
    store: &LocalGatewayStore,
    paths: &IkarosPaths,
    workspace: &Path,
    agent_override: Option<&str>,
) -> Result<GatewayDrainReport> {
    let effective_agent = message.agent.as_deref().or(agent_override);
    match message.kind {
        GatewayMessageKind::Chat => {
            drain_chat_message(store, &message, paths, workspace, effective_agent).await
        }
        GatewayMessageKind::Task => {
            drain_task_message(store, &message, paths, workspace, effective_agent).await
        }
    }
}

async fn drain_chat_message(
    store: &LocalGatewayStore,
    message: &GatewayMessage,
    paths: &IkarosPaths,
    workspace: &Path,
    agent: Option<&str>,
) -> Result<GatewayDrainReport> {
    let session_id = gateway_session_id(message);
    let session_source = gateway_session_source(message);
    match run_chat_message(
        &message.content,
        paths,
        workspace,
        agent,
        ChatRunOptions {
            session_id: Some(session_id.to_string()),
            session_source: Some(session_source),
            ..ChatRunOptions::default()
        },
    )
    .await
    {
        Ok(chat) => {
            let summary = format!(
                "chat response generated by {}/{}",
                chat.provider, chat.model
            );
            let update =
                store.record_status(&message.id, GatewayMessageStatus::Processed, &summary)?;
            let delivery = store.deliver(&message.id, "chat_response", chat.content)?;
            record_gateway_delivery_session(
                paths,
                workspace,
                agent,
                message,
                GatewayMessageStatus::Processed,
                &summary,
                Some(&delivery),
            )?;
            Ok(GatewayDrainReport {
                message_id: message.id.clone(),
                kind: "chat".into(),
                status: GatewayMessageStatus::Processed,
                summary,
                context: Some(GatewayDrainContext {
                    memory_hits: chat.memory_hits,
                    rag_hits: chat.rag_hits,
                }),
                provider: Some(chat.provider),
                model: Some(chat.model),
                streamed: Some(chat.streamed),
                stream_chunks: Some(chat.stream_chunks.len()),
                audit: Some(chat.audit_path),
                model_usage: Some(chat.model_usage_path),
                update,
                delivery: Some(delivery),
                task_report: None,
            })
        }
        Err(error) => {
            let report = record_gateway_error(store, &message.id, "chat", error.to_string())?;
            record_gateway_delivery_session(
                paths,
                workspace,
                agent,
                message,
                GatewayMessageStatus::Failed,
                &report.summary,
                None,
            )?;
            Ok(report)
        }
    }
}

async fn drain_task_message(
    store: &LocalGatewayStore,
    message: &GatewayMessage,
    paths: &IkarosPaths,
    workspace: &Path,
    agent: Option<&str>,
) -> Result<GatewayDrainReport> {
    let session_id = gateway_session_id(message);
    let turn_id = gateway_turn_id(&message.id);
    let task_options = TaskRunOptions::agent_loop(false).with_session(
        session_id.to_string(),
        turn_id.to_string(),
        gateway_session_source(message),
    );
    match execute_task_text_with_options(
        message.content.clone(),
        task_options,
        paths,
        workspace,
        agent,
    )
    .await
    {
        Ok(task_execution) => {
            let task_report = task_execution.report;
            let succeeded = task_report_succeeded(&task_report);
            let status = if succeeded {
                GatewayMessageStatus::Processed
            } else {
                GatewayMessageStatus::Failed
            };
            let summary = task_report_summary(
                &task_report,
                format!("completed {} gateway task step(s)", task_report.steps.len()),
            );
            let report_json = serde_json::to_string_pretty(&task_report)?;
            let update = store.record_status(&message.id, status.clone(), &summary)?;
            let delivery = store.deliver(&message.id, "task_report", report_json)?;
            record_gateway_task_session(GatewayTaskSessionInput {
                paths,
                workspace,
                agent,
                message,
                status: status.clone(),
                summary: &summary,
                delivery: Some(&delivery),
                task_report: Some(&task_report),
            })?;
            Ok(GatewayDrainReport {
                message_id: message.id.clone(),
                kind: "task".into(),
                status,
                summary,
                context: None,
                provider: None,
                model: None,
                streamed: None,
                stream_chunks: None,
                audit: None,
                model_usage: None,
                update,
                delivery: Some(delivery),
                task_report: Some(task_report),
            })
        }
        Err(error) => {
            let report = record_gateway_error(store, &message.id, "task", error.to_string())?;
            record_gateway_task_session(GatewayTaskSessionInput {
                paths,
                workspace,
                agent,
                message,
                status: GatewayMessageStatus::Failed,
                summary: &report.summary,
                delivery: None,
                task_report: None,
            })?;
            Ok(report)
        }
    }
}

fn record_gateway_error(
    store: &LocalGatewayStore,
    id: &str,
    kind: &str,
    error: String,
) -> Result<GatewayDrainReport> {
    let summary = redact_secrets(&error);
    let update = store.record_status(id, GatewayMessageStatus::Failed, &summary)?;
    Ok(GatewayDrainReport {
        message_id: id.into(),
        kind: kind.into(),
        status: GatewayMessageStatus::Failed,
        summary,
        context: None,
        provider: None,
        model: None,
        streamed: None,
        stream_chunks: None,
        audit: None,
        model_usage: None,
        update,
        delivery: None,
        task_report: None,
    })
}

fn record_gateway_delivery_session(
    paths: &IkarosPaths,
    workspace: &Path,
    agent: Option<&str>,
    message: &GatewayMessage,
    status: GatewayMessageStatus,
    summary: &str,
    delivery: Option<&ikaros_gateway::GatewayDelivery>,
) -> Result<()> {
    let target = runtime_session_target(paths, workspace, agent)?;
    let session_id = gateway_session_id(message);
    upsert_runtime_session(&target, &session_id, gateway_session_source(message))?;
    let turn_id = gateway_turn_id(&message.id);
    let parent_entry_id = active_leaf_entry_id(&target, &session_id)?;
    let delivery_value = delivery.map(|delivery| {
        json!({
            "delivery_id": &delivery.id,
            "kind": &delivery.kind,
            "message_id": &delivery.message_id,
            "created_at": &delivery.created_at,
        })
    });
    append_runtime_session_entry(RuntimeSessionEntryInput {
        target: &target,
        session_id: &session_id,
        parent_entry_id,
        turn_id: &turn_id,
        kind: SessionEntryKind::Custom,
        visible_text: Some(redact_secrets(summary)),
        payload: delivery_payload(
            "gateway_delivery",
            gateway_status_str(&status),
            summary,
            delivery_value,
        ),
    })?;
    Ok(())
}

struct GatewayTaskSessionInput<'a> {
    paths: &'a IkarosPaths,
    workspace: &'a Path,
    agent: Option<&'a str>,
    message: &'a GatewayMessage,
    status: GatewayMessageStatus,
    summary: &'a str,
    delivery: Option<&'a ikaros_gateway::GatewayDelivery>,
    task_report: Option<&'a TaskExecutionReport>,
}

fn record_gateway_task_session(input: GatewayTaskSessionInput<'_>) -> Result<()> {
    let target = runtime_session_target(input.paths, input.workspace, input.agent)?;
    let session_id = gateway_session_id(input.message);
    upsert_runtime_session(&target, &session_id, gateway_session_source(input.message))?;
    let turn_id = gateway_turn_id(&input.message.id);
    append_runtime_session_event(
        &target,
        &session_id,
        &turn_id,
        AgentEventSource::Runtime,
        AgentEventKind::SessionStart,
        json!({
            "source": "gateway",
            "message_id": &input.message.id,
            "kind": gateway_message_kind(&input.message.kind),
        }),
    )?;
    append_runtime_session_event(
        &target,
        &session_id,
        &turn_id,
        AgentEventSource::Runtime,
        AgentEventKind::TurnStart,
        json!({
            "source": "gateway",
            "message_id": &input.message.id,
            "kind": gateway_message_kind(&input.message.kind),
        }),
    )?;
    let parent_entry_id = active_leaf_entry_id(&target, &session_id)?;
    let user_entry_id = append_runtime_session_entry(RuntimeSessionEntryInput {
        target: &target,
        session_id: &session_id,
        parent_entry_id,
        turn_id: &turn_id,
        kind: SessionEntryKind::UserMessage,
        visible_text: Some(redact_secrets(&input.message.content)),
        payload: json!({
            "role": "user",
            "source": "gateway",
            "message_id": &input.message.id,
            "kind": gateway_message_kind(&input.message.kind),
            "content": redact_secrets(&input.message.content),
        }),
    })?;
    append_runtime_session_event(
        &target,
        &session_id,
        &turn_id,
        AgentEventSource::User,
        AgentEventKind::UserMessage,
        json!({
            "content": redact_secrets(&input.message.content),
        }),
    )?;
    let delivery = input.delivery.map(|delivery| {
        json!({
            "delivery_id": &delivery.id,
            "kind": &delivery.kind,
            "message_id": &delivery.message_id,
            "created_at": &delivery.created_at,
        })
    });
    append_runtime_session_entry(RuntimeSessionEntryInput {
        target: &target,
        session_id: &session_id,
        parent_entry_id: Some(user_entry_id),
        turn_id: &turn_id,
        kind: SessionEntryKind::Custom,
        visible_text: Some(redact_secrets(input.summary)),
        payload: json!({
            "role": "runtime",
            "source": "gateway",
            "message_id": &input.message.id,
            "status": gateway_status_str(&input.status),
            "summary": redact_secrets(input.summary),
            "task_id": input.task_report.map(|report| report.task_id.as_str()),
            "task_state": input.task_report.map(|report| format!("{:?}", report.state)),
            "step_count": input.task_report.map(|report| report.steps.len()),
            "delivery": delivery.unwrap_or(serde_json::Value::Null),
        }),
    })?;
    if input.status == GatewayMessageStatus::Failed {
        append_runtime_session_event(
            &target,
            &session_id,
            &turn_id,
            AgentEventSource::Runtime,
            AgentEventKind::Error,
            json!({
                "source": "gateway",
                "message_id": &input.message.id,
                "summary": redact_secrets(input.summary),
            }),
        )?;
    }
    append_runtime_session_event(
        &target,
        &session_id,
        &turn_id,
        AgentEventSource::Runtime,
        AgentEventKind::TurnEnd,
        json!({
            "source": "gateway",
            "message_id": &input.message.id,
            "status": gateway_status_str(&input.status),
        }),
    )
}

fn gateway_status_str(status: &GatewayMessageStatus) -> &'static str {
    match status {
        GatewayMessageStatus::Pending => "pending",
        GatewayMessageStatus::Processing => "processing",
        GatewayMessageStatus::Processed => "processed",
        GatewayMessageStatus::Failed => "failed",
    }
}
