// SPDX-License-Identifier: GPL-3.0-only

use super::types::{GatewayDrainContext, GatewayDrainReport};
use crate::{
    ChatRunOptions, execute_task_for_automation, run_chat_message, task_report_succeeded,
    task_report_summary,
};
use ikaros_core::{IkarosPaths, Result, redact_secrets};
use ikaros_gateway::{GatewayMessage, GatewayMessageKind, GatewayMessageStatus, LocalGatewayStore};
use std::path::Path;

pub async fn drain_gateway_messages(
    messages: Vec<GatewayMessage>,
    store: &LocalGatewayStore,
    paths: &IkarosPaths,
    workspace: &Path,
    agent_override: Option<&str>,
) -> Result<Vec<GatewayDrainReport>> {
    let mut reports = Vec::new();
    for message in messages {
        reports
            .push(drain_gateway_message(message, store, paths, workspace, agent_override).await?);
    }
    Ok(reports)
}

pub async fn drain_gateway_message(
    message: GatewayMessage,
    store: &LocalGatewayStore,
    paths: &IkarosPaths,
    workspace: &Path,
    agent_override: Option<&str>,
) -> Result<GatewayDrainReport> {
    let id = message.id;
    let content = message.content;
    let agent = message.agent;
    let effective_agent = agent.as_deref().or(agent_override);
    match message.kind {
        GatewayMessageKind::Chat => {
            drain_chat_message(store, &id, &content, paths, workspace, effective_agent).await
        }
        GatewayMessageKind::Task => {
            drain_task_message(store, &id, content, paths, workspace, effective_agent).await
        }
    }
}

async fn drain_chat_message(
    store: &LocalGatewayStore,
    id: &str,
    content: &str,
    paths: &IkarosPaths,
    workspace: &Path,
    agent: Option<&str>,
) -> Result<GatewayDrainReport> {
    match run_chat_message(content, paths, workspace, agent, ChatRunOptions::default()).await {
        Ok(chat) => {
            let summary = format!(
                "chat response generated by {}/{}",
                chat.provider, chat.model
            );
            let update = store.record_status(id, GatewayMessageStatus::Processed, &summary)?;
            let delivery = store.deliver(id, "chat_response", chat.content)?;
            Ok(GatewayDrainReport {
                message_id: id.into(),
                kind: "chat".into(),
                status: GatewayMessageStatus::Processed,
                summary,
                context: Some(GatewayDrainContext {
                    memory_hits: chat.memory_hits,
                    rag_hits: chat.rag_hits,
                }),
                provider: Some(chat.provider),
                model: Some(chat.model),
                streamed: Some(chat.streamed),
                stream_chunks: Some(chat.stream_chunks.len()),
                audit: Some(chat.audit_path),
                model_usage: Some(chat.model_usage_path),
                update,
                delivery: Some(delivery),
                task_report: None,
            })
        }
        Err(error) => record_gateway_error(store, id, "chat", error.to_string()),
    }
}

async fn drain_task_message(
    store: &LocalGatewayStore,
    id: &str,
    content: String,
    paths: &IkarosPaths,
    workspace: &Path,
    agent: Option<&str>,
) -> Result<GatewayDrainReport> {
    match execute_task_for_automation(content, paths, workspace, agent).await {
        Ok(task_report) => {
            let succeeded = task_report_succeeded(&task_report);
            let status = if succeeded {
                GatewayMessageStatus::Processed
            } else {
                GatewayMessageStatus::Failed
            };
            let summary = task_report_summary(
                &task_report,
                format!("completed {} gateway task step(s)", task_report.steps.len()),
            );
            let report_json = serde_json::to_string_pretty(&task_report)?;
            let update = store.record_status(id, status.clone(), &summary)?;
            let delivery = store.deliver(id, "task_report", report_json)?;
            Ok(GatewayDrainReport {
                message_id: id.into(),
                kind: "task".into(),
                status,
                summary,
                context: None,
                provider: None,
                model: None,
                streamed: None,
                stream_chunks: None,
                audit: None,
                model_usage: None,
                update,
                delivery: Some(delivery),
                task_report: Some(task_report),
            })
        }
        Err(error) => record_gateway_error(store, id, "task", error.to_string()),
    }
}

fn record_gateway_error(
    store: &LocalGatewayStore,
    id: &str,
    kind: &str,
    error: String,
) -> Result<GatewayDrainReport> {
    let summary = redact_secrets(&error);
    let update = store.record_status(id, GatewayMessageStatus::Failed, &summary)?;
    Ok(GatewayDrainReport {
        message_id: id.into(),
        kind: kind.into(),
        status: GatewayMessageStatus::Failed,
        summary,
        context: None,
        provider: None,
        model: None,
        streamed: None,
        stream_chunks: None,
        audit: None,
        model_usage: None,
        update,
        delivery: None,
        task_report: None,
    })
}
