// SPDX-License-Identifier: GPL-3.0-only

use super::recording::{
    GatewayTaskSessionInput, record_gateway_delivery_session, record_gateway_task_session,
};
use super::status::{
    current_gateway_status, gateway_status_str, record_gateway_error,
    record_gateway_status_for_drain,
};
use super::types::{
    GatewayChatDrainContext, GatewayDrainContext, GatewayDrainReport, GatewayMessageDrainContext,
    GatewayTaskDrainContext, GatewayWorkerTickReport,
};
use crate::chat::{ChatRunOptions, run_chat_message_with_context};
use crate::task_loop::{
    TaskRunOptions, execute_task_text_with_context, task_report_succeeded, task_report_summary,
};
use ikaros_core::{IkarosError, Result};
use ikaros_protocol::{GatewayMessage, GatewayMessageKind, GatewayMessageStatus};
use ikaros_state::gateway::LocalGatewayStore;
use ikaros_state::session::{
    RuntimeSessionTarget, gateway_message_kind, gateway_session_id, gateway_session_source,
    gateway_turn_id,
};

pub async fn drain_gateway_message_with_context(
    message: GatewayMessage,
    store: &LocalGatewayStore,
    context: GatewayMessageDrainContext<'_>,
) -> Result<GatewayDrainReport> {
    match (message.kind.clone(), context) {
        (GatewayMessageKind::Chat, GatewayMessageDrainContext::Chat(context)) => {
            drain_chat_message_with_context(store, &message, context).await
        }
        (GatewayMessageKind::Task, GatewayMessageDrainContext::Task(context)) => {
            drain_task_message_with_context(store, &message, context).await
        }
        (kind, _) => Err(IkarosError::Message(format!(
            "gateway drain context does not match message kind {}",
            gateway_message_kind(&kind)
        ))),
    }
}

pub fn record_gateway_message_preflight_failure(
    message: GatewayMessage,
    store: &LocalGatewayStore,
    session_target: &RuntimeSessionTarget,
    error: IkarosError,
) -> Result<GatewayDrainReport> {
    let kind = gateway_message_kind(&message.kind);
    let report = record_gateway_error(store, &message, kind, error.to_string())?;
    match message.kind {
        GatewayMessageKind::Chat => record_gateway_delivery_session(
            session_target,
            &message,
            report.status.clone(),
            &report.summary,
            None,
        )?,
        GatewayMessageKind::Task => record_gateway_task_session(GatewayTaskSessionInput {
            target: session_target,
            message: &message,
            status: report.status.clone(),
            summary: &report.summary,
            delivery: None,
            task_report: None,
        })?,
    }
    Ok(report)
}

pub async fn run_gateway_worker_tick_with_contexts<F, Fut>(
    store: &LocalGatewayStore,
    limit: usize,
    mut drain: F,
) -> Result<GatewayWorkerTickReport>
where
    F: FnMut(GatewayMessage) -> Fut,
    Fut: std::future::Future<Output = Result<GatewayDrainReport>>,
{
    if limit == 0 {
        return Err(IkarosError::Message(
            "message worker limit must be greater than zero".into(),
        ));
    }
    let messages = store.claim_pending(limit)?;
    let pending = messages.len();
    let mut reports = Vec::new();
    for message in messages {
        reports.push(drain(message).await?);
    }
    Ok(GatewayWorkerTickReport {
        kind: "gateway_worker_tick".into(),
        pending,
        drained: reports.len(),
        reports,
    })
}

async fn drain_chat_message_with_context(
    store: &LocalGatewayStore,
    message: &GatewayMessage,
    context: GatewayChatDrainContext<'_>,
) -> Result<GatewayDrainReport> {
    let session_id = gateway_session_id(message);
    let session_source = gateway_session_source(message);
    match run_chat_message_with_context(
        &message.content,
        ChatRunOptions {
            session_id: Some(session_id.to_string()),
            turn_id: Some(gateway_turn_id(&message.id).to_string()),
            session_source: Some(session_source),
            safe_tools: message.safe_tools,
            ..ChatRunOptions::default()
        },
        context.chat,
    )
    .await
    {
        Ok(chat) => {
            let summary = format!(
                "chat response generated by {}/{}",
                chat.provider, chat.model
            );
            let update = record_gateway_status_for_drain(
                store,
                message,
                GatewayMessageStatus::Processed,
                &summary,
            )?;
            if update.is_none() {
                let status = current_gateway_status(store, &message.id)?
                    .unwrap_or(GatewayMessageStatus::Cancelled);
                let summary = format!(
                    "gateway message claim no longer active; current_status={}",
                    gateway_status_str(&status)
                );
                record_gateway_delivery_session(
                    context.session_target,
                    message,
                    status.clone(),
                    &summary,
                    None,
                )?;
                return Ok(GatewayDrainReport {
                    message_id: message.id.clone(),
                    kind: "chat".into(),
                    status,
                    summary,
                    context: Some(GatewayDrainContext {
                        memory_hits: chat.memory_hits,
                        rag_hits: chat.rag_hits,
                    }),
                    provider: Some(chat.provider),
                    model: Some(chat.model),
                    streamed: Some(chat.streamed),
                    stream_chunks: Some(chat.stream_chunks.len()),
                    audit: Some(chat.audit_path),
                    model_usage: Some(chat.model_usage_path),
                    update: None,
                    delivery: None,
                    task_report: None,
                });
            }
            let delivery = store.deliver(&message.id, "chat_response", chat.content)?;
            record_gateway_delivery_session(
                context.session_target,
                message,
                GatewayMessageStatus::Processed,
                &summary,
                Some(&delivery),
            )?;
            Ok(GatewayDrainReport {
                message_id: message.id.clone(),
                kind: "chat".into(),
                status: GatewayMessageStatus::Processed,
                summary,
                context: Some(GatewayDrainContext {
                    memory_hits: chat.memory_hits,
                    rag_hits: chat.rag_hits,
                }),
                provider: Some(chat.provider),
                model: Some(chat.model),
                streamed: Some(chat.streamed),
                stream_chunks: Some(chat.stream_chunks.len()),
                audit: Some(chat.audit_path),
                model_usage: Some(chat.model_usage_path),
                update,
                delivery: Some(delivery),
                task_report: None,
            })
        }
        Err(error) => {
            let report = record_gateway_error(store, message, "chat", error.to_string())?;
            record_gateway_delivery_session(
                context.session_target,
                message,
                report.status.clone(),
                &report.summary,
                None,
            )?;
            Ok(report)
        }
    }
}

async fn drain_task_message_with_context(
    store: &LocalGatewayStore,
    message: &GatewayMessage,
    context: GatewayTaskDrainContext<'_>,
) -> Result<GatewayDrainReport> {
    let session_id = gateway_session_id(message);
    let turn_id = gateway_turn_id(&message.id);
    let task_options = TaskRunOptions::deterministic(false)
        .with_session(
            session_id.to_string(),
            turn_id.to_string(),
            gateway_session_source(message),
        )
        .with_safe_tools(message.safe_tools);
    match execute_task_text_with_context(message.content.clone(), task_options, context.task).await
    {
        Ok(task_execution) => {
            let task_report = task_execution.report;
            let succeeded = task_report_succeeded(&task_report);
            let status = if succeeded {
                GatewayMessageStatus::Processed
            } else {
                GatewayMessageStatus::Failed
            };
            let summary = task_report_summary(
                &task_report,
                format!("completed {} gateway task step(s)", task_report.steps.len()),
            );
            let report_json = serde_json::to_string_pretty(&task_report)?;
            let update = record_gateway_status_for_drain(store, message, status.clone(), &summary)?;
            if update.is_none() {
                let status = current_gateway_status(store, &message.id)?
                    .unwrap_or(GatewayMessageStatus::Cancelled);
                let summary = format!(
                    "gateway message claim no longer active; current_status={}",
                    gateway_status_str(&status)
                );
                record_gateway_task_session(GatewayTaskSessionInput {
                    target: context.session_target,
                    message,
                    status: status.clone(),
                    summary: &summary,
                    delivery: None,
                    task_report: Some(&task_report),
                })?;
                return Ok(GatewayDrainReport {
                    message_id: message.id.clone(),
                    kind: "task".into(),
                    status,
                    summary,
                    context: None,
                    provider: None,
                    model: None,
                    streamed: None,
                    stream_chunks: None,
                    audit: None,
                    model_usage: None,
                    update: None,
                    delivery: None,
                    task_report: Some(task_report),
                });
            }
            let delivery = store.deliver(&message.id, "task_report", report_json)?;
            record_gateway_task_session(GatewayTaskSessionInput {
                target: context.session_target,
                message,
                status: status.clone(),
                summary: &summary,
                delivery: Some(&delivery),
                task_report: Some(&task_report),
            })?;
            Ok(GatewayDrainReport {
                message_id: message.id.clone(),
                kind: "task".into(),
                status,
                summary,
                context: None,
                provider: None,
                model: None,
                streamed: None,
                stream_chunks: None,
                audit: None,
                model_usage: None,
                update,
                delivery: Some(delivery),
                task_report: Some(task_report),
            })
        }
        Err(error) => {
            let report = record_gateway_error(store, message, "task", error.to_string())?;
            record_gateway_task_session(GatewayTaskSessionInput {
                target: context.session_target,
                message,
                status: report.status.clone(),
                summary: &report.summary,
                delivery: None,
                task_report: None,
            })?;
            Ok(report)
        }
    }
}
