from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Final

from .spec import protocol_manifest

_RUNTIME_ROOT: Final = Path(__file__).resolve().parents[3]
_REPOSITORY_ROOT: Final = _RUNTIME_ROOT.parent
_MANIFEST_PATH: Final = _RUNTIME_ROOT / "protocol" / "runtime-protocol.json"
_TYPESCRIPT_PATH: Final = (
    _REPOSITORY_ROOT
    / "ikaros"
    / "desktop"
    / "src"
    / "shared"
    / "generated"
    / "runtimeProtocol.ts"
)


def _manifest_text() -> str:
    return json.dumps(protocol_manifest(), ensure_ascii=False, indent=2) + "\n"


def _typescript_text() -> str:
    manifest_json = json.dumps(protocol_manifest(), ensure_ascii=False, indent=2)
    return (
        "// Generated by `python -m ikaros_runtime.protocol.generate`.\n"
        "// Do not edit this file by hand.\n\n"
        f"export const RUNTIME_PROTOCOL_MANIFEST = {manifest_json} as const;\n\n"
        "export const RUNTIME_PROTOCOL_VERSION = "
        "RUNTIME_PROTOCOL_MANIFEST.protocolVersion;\n"
        "export const RUNTIME_SERVER_NAME = RUNTIME_PROTOCOL_MANIFEST.serverName;\n"
        "export const RUNTIME_INITIALIZE_METHOD = "
        "RUNTIME_PROTOCOL_MANIFEST.initializeMethod;\n"
        "export const RUNTIME_RPC_METHODS = RUNTIME_PROTOCOL_MANIFEST.rpcMethods;\n"
        "export type RuntimeRpcMethod = (typeof RUNTIME_RPC_METHODS)[number];\n"
        "export const RUNTIME_NOTIFICATION_METHODS = "
        "RUNTIME_PROTOCOL_MANIFEST.notificationMethods;\n"
        "export type RuntimeNotificationMethod = "
        "(typeof RUNTIME_NOTIFICATION_METHODS)[number];\n"
        "export const RUNTIME_JOURNAL_EVENT_SCHEMA_VERSION = "
        "RUNTIME_PROTOCOL_MANIFEST.journal.schemaVersion;\n"
        "export const RUNTIME_JOURNAL_EVENT_TYPES = "
        "RUNTIME_PROTOCOL_MANIFEST.journal.eventTypes;\n"
        "export type RuntimeJournalEventType = "
        "(typeof RUNTIME_JOURNAL_EVENT_TYPES)[number];\n"
        "export const RUNTIME_PROVIDER_TOOL_IDS = "
        "RUNTIME_PROTOCOL_MANIFEST.providerToolIds;\n"
        "export type RuntimeProviderToolId = "
        "(typeof RUNTIME_PROVIDER_TOOL_IDS)[number];\n"
    )


def _expected_files() -> tuple[tuple[Path, str], ...]:
    return (
        (_MANIFEST_PATH, _manifest_text()),
        (_TYPESCRIPT_PATH, _typescript_text()),
    )


def _check() -> int:
    drifted = [
        str(path.relative_to(_REPOSITORY_ROOT))
        for path, expected in _expected_files()
        if not path.is_file() or path.read_text(encoding="utf-8") != expected
    ]
    if drifted:
        for path in drifted:
            print(f"protocol generated file is stale: {path}")
        return 1
    return 0


def _write() -> None:
    for path, content in _expected_files():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the Ikaros Runtime protocol contract")
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when committed generated files differ from protocol.spec",
    )
    args = parser.parse_args()
    if args.check:
        return _check()
    _write()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
