// SPDX-License-Identifier: GPL-3.0-only

use super::types::{GatewayDrainContext, GatewayDrainReport};
use crate::{
    ChatRunOptions, TaskRunOptions, execute_task_text_with_options, run_chat_message,
    task_report_succeeded, task_report_summary,
};
use ikaros_core::{IkarosPaths, Result, redact_secrets};
use ikaros_gateway::{GatewayMessage, GatewayMessageKind, GatewayMessageStatus, LocalGatewayStore};
use std::path::Path;

mod session_recording;
mod status;

use crate::session::{gateway_session_id, gateway_session_source, gateway_turn_id};
use session_recording::{
    GatewayTaskSessionInput, record_gateway_delivery_session, record_gateway_task_session,
};
use status::{
    current_gateway_status, gateway_status_str, record_gateway_failure_for_drain,
    record_gateway_status_for_drain,
};

pub async fn drain_gateway_messages(
    messages: Vec<GatewayMessage>,
    store: &LocalGatewayStore,
    paths: &IkarosPaths,
    workspace: &Path,
    agent_override: Option<&str>,
) -> Result<Vec<GatewayDrainReport>> {
    let mut reports = Vec::new();
    for message in messages {
        reports
            .push(drain_gateway_message(message, store, paths, workspace, agent_override).await?);
    }
    Ok(reports)
}

pub async fn drain_gateway_message(
    message: GatewayMessage,
    store: &LocalGatewayStore,
    paths: &IkarosPaths,
    workspace: &Path,
    agent_override: Option<&str>,
) -> Result<GatewayDrainReport> {
    let effective_agent = message.agent.as_deref().or(agent_override);
    match message.kind {
        GatewayMessageKind::Chat => {
            drain_chat_message(store, &message, paths, workspace, effective_agent).await
        }
        GatewayMessageKind::Task => {
            drain_task_message(store, &message, paths, workspace, effective_agent).await
        }
    }
}

async fn drain_chat_message(
    store: &LocalGatewayStore,
    message: &GatewayMessage,
    paths: &IkarosPaths,
    workspace: &Path,
    agent: Option<&str>,
) -> Result<GatewayDrainReport> {
    let session_id = gateway_session_id(message);
    let session_source = gateway_session_source(message);
    match run_chat_message(
        &message.content,
        paths,
        workspace,
        agent,
        ChatRunOptions {
            session_id: Some(session_id.to_string()),
            turn_id: Some(gateway_turn_id(&message.id).to_string()),
            session_source: Some(session_source),
            safe_tools: message.safe_tools,
            ..ChatRunOptions::default()
        },
    )
    .await
    {
        Ok(chat) => {
            let summary = format!(
                "chat response generated by {}/{}",
                chat.provider, chat.model
            );
            let update = record_gateway_status_for_drain(
                store,
                message,
                GatewayMessageStatus::Processed,
                &summary,
            )?;
            if update.is_none() {
                let status = current_gateway_status(store, &message.id)?
                    .unwrap_or(GatewayMessageStatus::Cancelled);
                let summary = format!(
                    "gateway message claim no longer active; current_status={}",
                    gateway_status_str(&status)
                );
                record_gateway_delivery_session(
                    paths,
                    workspace,
                    agent,
                    message,
                    status.clone(),
                    &summary,
                    None,
                )?;
                return Ok(GatewayDrainReport {
                    message_id: message.id.clone(),
                    kind: "chat".into(),
                    status,
                    summary,
                    context: Some(GatewayDrainContext {
                        memory_hits: chat.memory_hits,
                        rag_hits: chat.rag_hits,
                    }),
                    provider: Some(chat.provider),
                    model: Some(chat.model),
                    streamed: Some(chat.streamed),
                    stream_chunks: Some(chat.stream_chunks.len()),
                    audit: Some(chat.audit_path),
                    model_usage: Some(chat.model_usage_path),
                    update: None,
                    delivery: None,
                    task_report: None,
                });
            }
            let delivery = store.deliver(&message.id, "chat_response", chat.content)?;
            record_gateway_delivery_session(
                paths,
                workspace,
                agent,
                message,
                GatewayMessageStatus::Processed,
                &summary,
                Some(&delivery),
            )?;
            Ok(GatewayDrainReport {
                message_id: message.id.clone(),
                kind: "chat".into(),
                status: GatewayMessageStatus::Processed,
                summary,
                context: Some(GatewayDrainContext {
                    memory_hits: chat.memory_hits,
                    rag_hits: chat.rag_hits,
                }),
                provider: Some(chat.provider),
                model: Some(chat.model),
                streamed: Some(chat.streamed),
                stream_chunks: Some(chat.stream_chunks.len()),
                audit: Some(chat.audit_path),
                model_usage: Some(chat.model_usage_path),
                update,
                delivery: Some(delivery),
                task_report: None,
            })
        }
        Err(error) => {
            let report = record_gateway_error(store, message, "chat", error.to_string())?;
            record_gateway_delivery_session(
                paths,
                workspace,
                agent,
                message,
                report.status.clone(),
                &report.summary,
                None,
            )?;
            Ok(report)
        }
    }
}

async fn drain_task_message(
    store: &LocalGatewayStore,
    message: &GatewayMessage,
    paths: &IkarosPaths,
    workspace: &Path,
    agent: Option<&str>,
) -> Result<GatewayDrainReport> {
    let session_id = gateway_session_id(message);
    let turn_id = gateway_turn_id(&message.id);
    let task_options = TaskRunOptions::agent_loop(false)
        .with_session(
            session_id.to_string(),
            turn_id.to_string(),
            gateway_session_source(message),
        )
        .with_safe_tools(message.safe_tools);
    match execute_task_text_with_options(
        message.content.clone(),
        task_options,
        paths,
        workspace,
        agent,
    )
    .await
    {
        Ok(task_execution) => {
            let task_report = task_execution.report;
            let succeeded = task_report_succeeded(&task_report);
            let status = if succeeded {
                GatewayMessageStatus::Processed
            } else {
                GatewayMessageStatus::Failed
            };
            let summary = task_report_summary(
                &task_report,
                format!("completed {} gateway task step(s)", task_report.steps.len()),
            );
            let report_json = serde_json::to_string_pretty(&task_report)?;
            let update = record_gateway_status_for_drain(store, message, status.clone(), &summary)?;
            if update.is_none() {
                let status = current_gateway_status(store, &message.id)?
                    .unwrap_or(GatewayMessageStatus::Cancelled);
                let summary = format!(
                    "gateway message claim no longer active; current_status={}",
                    gateway_status_str(&status)
                );
                record_gateway_task_session(GatewayTaskSessionInput {
                    paths,
                    workspace,
                    agent,
                    message,
                    status: status.clone(),
                    summary: &summary,
                    delivery: None,
                    task_report: Some(&task_report),
                })?;
                return Ok(GatewayDrainReport {
                    message_id: message.id.clone(),
                    kind: "task".into(),
                    status,
                    summary,
                    context: None,
                    provider: None,
                    model: None,
                    streamed: None,
                    stream_chunks: None,
                    audit: None,
                    model_usage: None,
                    update: None,
                    delivery: None,
                    task_report: Some(task_report),
                });
            }
            let delivery = store.deliver(&message.id, "task_report", report_json)?;
            record_gateway_task_session(GatewayTaskSessionInput {
                paths,
                workspace,
                agent,
                message,
                status: status.clone(),
                summary: &summary,
                delivery: Some(&delivery),
                task_report: Some(&task_report),
            })?;
            Ok(GatewayDrainReport {
                message_id: message.id.clone(),
                kind: "task".into(),
                status,
                summary,
                context: None,
                provider: None,
                model: None,
                streamed: None,
                stream_chunks: None,
                audit: None,
                model_usage: None,
                update,
                delivery: Some(delivery),
                task_report: Some(task_report),
            })
        }
        Err(error) => {
            let report = record_gateway_error(store, message, "task", error.to_string())?;
            record_gateway_task_session(GatewayTaskSessionInput {
                paths,
                workspace,
                agent,
                message,
                status: report.status.clone(),
                summary: &report.summary,
                delivery: None,
                task_report: None,
            })?;
            Ok(report)
        }
    }
}

#[cfg(test)]
pub(crate) fn gateway_toolsets_for_message(
    agent: &ikaros_core::ResolvedAgentProfile,
    message: &GatewayMessage,
) -> Result<ikaros_harness::ToolsetSelection> {
    if message.safe_tools {
        Ok(ikaros_harness::ToolsetSelection::new([
            ikaros_harness::Toolset::Core,
        ]))
    } else {
        crate::agent_toolset_selection(agent)
    }
}

fn record_gateway_error(
    store: &LocalGatewayStore,
    message: &GatewayMessage,
    kind: &str,
    error: String,
) -> Result<GatewayDrainReport> {
    let summary = redact_secrets(&error);
    let update = record_gateway_failure_for_drain(store, message, &summary)?;
    let status = match update.as_ref().map(|message| message.status.clone()) {
        Some(status) => status,
        None => current_gateway_status(store, &message.id)?.unwrap_or(GatewayMessageStatus::Failed),
    };
    Ok(GatewayDrainReport {
        message_id: message.id.clone(),
        kind: kind.into(),
        status,
        summary,
        context: None,
        provider: None,
        model: None,
        streamed: None,
        stream_chunks: None,
        audit: None,
        model_usage: None,
        update,
        delivery: None,
        task_report: None,
    })
}
